releaseTag: "d7700fdff50ba3b11e8100f50cca1a9fd8bd87e3"
config:
  appEnv: eks
api:
  image:
    repository: 257492816994.dkr.ecr.us-east-1.amazonaws.com/distributed-job-processing-system-api
celeryWorker:
  image:
    repository: 257492816994.dkr.ecr.us-east-1.amazonaws.com/distributed-job-processing-system-celery-worker
frontend:
  image:
    repository: 257492816994.dkr.ecr.us-east-1.amazonaws.com/distributed-job-processing-system-frontend
