services:
  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    environment:
      APP_ENV: local
      LOG_LEVEL: INFO
      API_HOST: 0.0.0.0
      API_PORT: 8000
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/jobs
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.worker
    environment:
      APP_ENV: local
      LOG_LEVEL: INFO
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/jobs
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobs"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:  # preserver across container restarts
  postgres_data:
