apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  annotations:
    distributed-jobs.dev/source-revision: {{ .Values.releaseTag | quote }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 8000
