{{- if .Values.applicationSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- toYaml .Values.applicationSecret.stringData | nindent 2 }}
{{- end }}