apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: {{ .Release.Namespace }}
  annotations:
    distributed-jobs.dev/source-revision: {{ .Values.releaseTag | quote }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  API_HOST: {{ .Values.config.apiHost | quote }}
  API_PORT: {{ .Values.config.apiPort | quote }}
  DEFAULT_MAXIMUM_ATTEMPT_COUNT: {{ .Values.config.defaultMaximumAttemptCount | quote }}
  API_PROXY_TARGET: {{ .Values.config.apiProxyTarget | quote }}
