apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    distributed-jobs.dev/source-revision: {{ .Values.releaseTag | quote }}
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 5173
      targetPort: 5173
