FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml README.md ./
COPY app ./app
COPY alembic.ini ./
COPY alembic ./alembic

RUN pip install --no-cache-dir uv \
    && uv pip install --system .

CMD ["celery", "-A", "app.worker.celery_app:celery_app", "worker", "--loglevel=info"]
